services:
  anki:
    platform: linux/amd64
    image: ghcr.io/adamtrnguyen/arete/anki-custom:latest
    container_name: anki-test
    environment:
      - PUID=1000
      - PGID=1000
      - ANKI_LANG=en
      - ANKI_VERSION=26.8.1
      - QT_QUICK_BACKEND=software
      - ANKI_NOHIGHDPI=1
      - ANKICONNECT_BIND_ADDRESS=0.0.0.0
    ports:
      - "3000:3000"
      - "8766:8765"
    volumes:
      - ./anki_data:/config
      - ../arete_ankiconnect:/config/.local/share/Anki2/addons21/arete_ankiconnect
    shm_size: "1gb"
    restart: unless-stopped
